version: "3.7"

services:
  postgres:
    image: postgres:9.5
    volumes:
      - postgresql:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - cachet
    restart: always

  cachet:
    image: cachethq/docker:latest
    ports:
      - 80:8000
    environment:
      - DB_DRIVER=pgsql
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_DATABASE=postgres
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_PREFIX=chq_
      - APP_KEY=${APP_KEY:-null}
      - APP_LOG=errorlog
      - APP_ENV=${APP_ENV:-production}
      - APP_DEBUG=false
      - DEBUG=false
    depends_on:
      - postgres
    networks:
      - cachet
    restart: on-failure


networks:
  cachet:
    driver: bridge
    name: cachet


volumes:
  postgresql:
