version: 2.1
executors:
  docker-publisher:
    environment:
      IMAGE_NAME: jonbackhaus/cachet
      # CACHET_VER:
      # ARCHIVE_URL: 
    docker:
      - image: circleci/buildpack-deps:stretch


jobs:
  build-x86-64:
    executor: docker-publisher
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: |
            docker build -t $IMAGE_NAME .
      - run:
          name: Archive Docker image
          command: docker save -o image.tar $IMAGE_NAME
      - persist_to_workspace:
          root: .
          paths:
            - ./image.tar
  build-arm32:
    executor: docker-publisher
    steps:
      - checkout
      - setup_remote_docker:
          version: 18.09.3
      - run:
          name: Build Docker image
          command: |
            docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
            docker build -t $IMAGE_NAME .
      - run:
          name: Archive Docker image
          command: docker save -o image.tar $IMAGE_NAME
      - persist_to_workspace:
          root: .
          paths:
            - ./image.tar

  publish:
    executor: docker-publisher
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - setup_remote_docker
      - run:
          name: Load archived Docker image
          command: docker load -i /tmp/workspace/image.tar
      - run:
          name: Publish Docker Image to Docker Hub
          command: |
            echo "$DOCKERHUB_TOKEN" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            COMMIT_TAGNAME=${CIRCLE_SHA1:0:7}; echo "COMMIT_TAGNAME=$COMMIT_TAGNAME"
            docker tag $IMAGE_NAME $IMAGE_NAME:latest
            docker tag $IMAGE_NAME $IMAGE_NAME:$COMMIT_TAGNAME
            docker push $IMAGE_NAME:latest
            docker push $IMAGE_NAME:$COMMIT_TAGNAME

  publish-branch:
    executor: docker-publisher
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - setup_remote_docker
      - run:
          name: Load archived Docker image
          command: docker load -i /tmp/workspace/image.tar
      - run:
          name: Publish Docker Image to Docker Hub
          command: |
            echo "$DOCKERHUB_TOKEN" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            docker tag $IMAGE_NAME $IMAGE_NAME:$CIRCLE_BRANCH
            docker push $IMAGE_NAME:$CIRCLE_BRANCH


workflows:
  version: 2
  build-master:
    jobs:
      - build-x86-64:
          filters:
            branches:
              only: master
      - publish:
          requires:
            - build-x86-64
          context: default
  build-branch:
    jobs:
      - build-x86-64:
          filters:
            branches:
              ignore: master
      - publish-branch:
          requires:
            - build-x86-64
          context: default
